config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :reports
  
  root 'static_homes#home'
  
  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

end

app/models/report.rb
class Report
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
  field :address, type: String
  field :city, type: String
  field :state, type: String
  field :zip, type: String
  field :body, type: String
  belongs_to :user

  validates :name, presence: true
  validates :body, presence: true

	def date_published
  	# self is implied and is not needed. this is an instance method
  	self.created_at.localtime.strftime("%A, %B %-d, %Y at %l:%M %p")
  end

  def full_address
    "#{self.address.titleize}\n#{self.city.capitalize}, #{self.state.upcase}. #{self.zip}"
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  field :name, type: String
  field :address, type: String
  field :city, type: String
  field :zip, type: Integer
  field :email, type: String
  field :password_digest, type: String
  attr_reader :password

  mount_uploader :image, AvatarUploader
  has_many :reports

  #here another way to validate presence of multiple things one line:
  # validates_presence_of :name, :email, :password

  #make sure that the name exist
  validates :name, presence: true
  #makes sure that email exist and is unique and declares the format
  validates :email, presence: true, uniqueness: { case_sensitive: false },
    format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :password, presence: true, length: { :within => 6..40 }, confirmation: true,
    :allow_blank => false, :on => :create
  validates :password, presence: true, length: { :within => 6..40 }, confirmation: true,
    :allow_blank => true, :on => :update

  #setter method
  def password=(unencrypted_password)
    unless unencrypted_password.empty?
      @password = unencrypted_password
      encrypted_password = BCrypt::Password.create(unencrypted_password)
      self.password_digest = encrypted_password
    end
  end

  def authenticate(unencrypted_password)
    if BCrypt::Password.new(self.password_digest) == unencrypted_password
      return self
    else
      return false
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	def index
		@reports = Report.all
	end	

	def show
		@report = Report.find(params[:id])
		# @comment = Comment.new
	end

	def new
		@report = Report.new
	end

	def create
		@report = Report.create(report_params)
		@report.user = current_user
		if @report.save
			redirect_to reports_path
		else
			render :new
		end
	end

	private

	def report_params
		params.require(:report).permit(:name, :address, :city, :state, :zip , :body, :user)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
  end

  def create
    @user = User.find_by(email: params[:login][:email])
    if @user && @user.authenticate(params[:login][:password])
      session[:user_id] = @user.id.to_s
      redirect_to @user
    else
      flash[:error] = "Invalid email or password"
      redirect_to login_path
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/static_homes_controller.rb
class StaticHomesController < ApplicationController
	def home
		@reports = Report.all
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :destroy, :edit, :update]

	def index
		@users = User.all
  end

  def show
  end

  def destroy
  	@user.destroy 
  	redirect_to users_url
  end

  def new
  	@user = User.new
  	@submit_message = 'Sign Up'	
  end

  def create
  	@user = User.new(user_params)
		if @user.save
			redirect_to @user
		else
			#redisplay the form that is created. 
			render 'new'
		end
  end

  def edit
		@submit_message = 'Edit Account'
	end


	def update
		if @user.update_attributes!(user_params)
			redirect_to @user
		else
			render 'edit'
		end
	end

  #only accessible from the controller
	private

	def set_user
		@user = User.find(params[:id])
	end

	def user_params
		params.require(:user).permit(:name, :email, :address, :city, :zip, :password, :password_confirmation, :image)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

end

app/helpers/static_homes_helper.rb
module StaticHomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrimeWatch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class='container-fluid' id="appmain">
		<div class='container'>
			<%= render 'shared/navigation' %>
			<%= yield %>
		</div>
	</div>
	</body>
</html>

app/views/reports/_form.html.haml
= form_for @report do |f|
	.form-group
		= f.label :name, class: "control-label"
		= f.text_field :name, class: "form-control"
	.form-group
		= f.label :address, class: "control-label"
		= f.text_field :address, class: "form-control"
	.form-group
		= f.label :city, class: "control-label"
		= f.text_field :city, class: "form-control"
	.form-group
		= f.label :state, class: "control-label"
		= f.text_field :state, class: "form-control"
	.form-group
		= f.label :zip, class: "control-label"
		= f.text_field :zip, class: "form-control"
	.form-group
		= f.label "What did you see?", class: "control-label"
		= f.text_area :body, rows: 5, class: "form-control"

	= f.submit 'Add a Report', class: "btn btn-danger"

app/views/reports/index.html.haml
%h1 All reports
- @reports.each do |report|
	.table.table-hover
	= link_to report.name.titleize, report
					

app/views/reports/new.html.haml
%h1 Create A Report
.row
	.col-sm-4
		- @report.errors.full_messages.each do |msg|
			%li.list-group-item.list-group-item-danger
			= msg
		= render 'form'

app/views/reports/show.html.haml
.jumbotron
	.container
		.row
			%h1
				= @report.name.titleize
		.row
			%p
				%small
					= " Reported by: #{@report.user.name}"
.row
	.col-md-6
		- if @report.address
			= simple_format @report.full_address
		%address
		.blockquote
			%p.lead
				= @report.body

app/views/shared/_navigation.html.haml
.row
	%nav.col-md-6
		.container
			%ul.nav.nav-tabs
				%li 
					= link_to 'Home', root_path
				%li
					= link_to 'Reports', reports_path
				%li
					- if session[:user_id] 
						= link_to "#{current_user.name}", user_path(session[:user_id])
				%li
					/ if the user id key exist it means the user is logged in. 
					- if session[:user_id]
						= link_to 'Log Out', logout_path, method: :delete
				- unless session[:user_id]
					%li
						= link_to 'Sign Up', new_user_path
	- unless current_user
		%nav.col-md-6.form-inline
			= form_for :login, url: {controller: :sessions, action: :create} do |f|
				= f.text_field :email, placeholder: :email, class: "form-control"
				=	f.password_field :password, placeholder: :password, class: "form-control"
				= f.submit "Login", :class => "btn btn-primary"



	

app/views/static_homes/home.html.haml
%h1.jumbotron.text-center
	- if current_user
		= "Welome, #{current_user.name}, to your Neighborhood Watch!"
	- else
		Welcome to your Neighborhood Watch
.row
	.col-md-6
		%p.lead
			Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
	.col-md-6
		.panel.panel-danger
			.panel-heading
				%h2.inline.text-center Latest Reports
			.panel-body
				- @reports.each do |report|
					.list-group
						%a.list-group-item{href: report_path(report) }
							%h4.list-group-item-heading
								%p.lead
									= report.name.titleize
							%p.list-group-item-text
								= truncate(report.body, length: 200, separator: ' ') 

app/views/users/_form.html.haml
= form_for @user do |f|
  .form-group
    = f.label :name, class: "control-label"
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label :address, class: "control-label"
    = f.text_field :address, class: "form-control"
  .form-group
    = f.label :city, class: "control-label"
    = f.text_field :city, class: "form-control"
  .form-group
    = f.label :zip, class: "control-label"
    = f.number_field :zip, class: "form-control"
  .form-group
    = f.label :email, class: "control-label" 
    = f.text_field :email, class: "form-control"
  .form-group
    = f.label :password, class: "control-label"
    = f.password_field :password, class: "form-control"
  .form-group
    = f.label :password_confirmation, class: "control-label"
    = f.password_field :password_confirmation, class: "form-control"
  %div
    = f.submit @submit_message, class: "btn btn-primary"  

app/views/users/edit.html.haml
.container-fluid
	.row
		.col-sm-4
			= render 'form'

app/views/users/index.html.haml
.row
	.col-sm-4
		%h1 Admin view
		%div
			%ul
				- @users.each do |user|
					%li
						= link_to user.name, user_path(user)

app/views/users/new.html.haml
.container-fluid
	.row
		.col-md-6
			%h1.text-center Sign up for an account
			= render 'form'
		.col-md-6
			- unless @user.errors.full_messages.empty?
				%h1.text-center Please fix your errors 
			%ul.list-group
				- @user.errors.full_messages.each do |msg|
					%li.list-group-item.list-group-item-danger
						= msg

app/views/users/show.html.haml
%h1 Account info
.row
	.col-md-3
		= @user.name
		%br
		= @user.email
		%br
		= @user.address
		%br
		= @user.city
		%br
		= @user.zip
		%br
		= link_to 'Edit your account', edit_user_path(@user)
	.col-md-6
		= link_to 'report a suspicious activity', new_report_path